### PR TITLE
Added support for increasing logging for a specific point in the tree

### PR DESCRIPTION
**Pull request by IdolfHatler**
Example:

```py
#!/usr/bin/env python
# Run with:
# $ ./doit.py LOG_FILE=doit.log
# or:
# $ ./doit.py DEBUG

from pwn import *
import logging

a   = getLogger('pwnlib.a')
ab  = getLogger('pwnlib.a.b')
abx = getLogger('pwnlib.a.b.x')

h1 = ab.addConsoleHandler(logging.DEBUG)
h2 = abx.addConsoleHandler(logging.DEBUG)

a.debug('test1')
ab.debug('test2')
abx.debug('test3')

ab.removeHandler(h1)

a.debug('test4')
ab.debug('test5')
abx.debug('test6')
```

### CODE REVIEW

**Comment by zachriggle** [comment]
This shouldn't be necessary with #421, as you can just use `.setLevel()`.

**Comment by zachriggle** [comment]
I think you accidentally a commit.

```
Traceback (most recent call last):
  File "./doit.py", line 8, in <module>
    h1 = ab.addConsoleHandler(logging.DEBUG)
AttributeError: 'Logger' object has no attribute 'addConsoleHandler'
```

**Comment by IdolfHatler** [comment]
I do not have that failure here. I do have another one though that was introduced recently. That is only a formatting issue.

**Comment by IdolfHatler** [comment]
Yes, the formatting issue was introduced in 6e33077081e20f46bb90a67eacd9cc475f12512c.

**Comment by IdolfHatler** [comment]
Rebased yet again. I still think this is the right solution.
